server:
  port: 8080
mybatis:
  mapper-locations: classpath:com.example.demo.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
spring:
  datasource:
    url:
    username:
    password:
    continue-on-error: true
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver



